#!/usr/bin/env python3
"""
bake_player_anims.py -- export character.b3d clips to a Lua table for the
client-side animation system (games/Proprietary_game/mods/player/player_anim).

The engine can only play one skeletal clip at a time, so player_anim samples and
blends poses itself in Lua. It cannot read .b3d files, so this script bakes the
per-bone keyframes of every clip listed in player_anim/clip_ranges.lua into
player_anim/anim_data.lua. The server ships that table to clients over an SSCSM
com channel at load time.

Keyframes are decimated (Ramer-Douglas-Peucker, exact kept values) since the
model bakes a key on every frame. Rotations are stored as xyzw quaternions.

    python b3d_opti_tools/bake_player_anims.py
    python b3d_opti_tools/bake_player_anims.py --pos-tol 0.02 --rot-tol 0.5

Needs numpy and b3dlib.py (same directory).
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from b3dlib import parse, slerp, quat_angle_deg  # noqa: E402
from b3d_decimate_keys import decimate_track  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.normpath(os.path.join(
    HERE, "..", "games", "Proprietary_game", "mods", "player", "player_anim"))
RANGES_LUA = os.path.join(MOD, "clip_ranges.lua")
OUT_LUA = os.path.join(MOD, "anim_data.lua")
MODEL = os.path.normpath(os.path.join(
    HERE, "..", "games", "Proprietary_game", "mods", "player",
    "player_model", "models", "character.b3d"))


def read_ranges():
    txt = open(RANGES_LUA, "r", encoding="utf-8").read()
    fps = int(re.search(r"fps\s*=\s*(\d+)", txt).group(1))
    bones = re.findall(r'"([A-Za-z_]+)"', txt.split("bones", 1)[1])
    clips = {}
    body = txt.split("clips", 1)[1]
    for name, a, b, tail in re.findall(
            r"(\w+)\s*=\s*{\s*(-?\d+),\s*(-?\d+)([^}]*)}", body):
        clips[name] = {
            "range": (int(a), int(b)),
            "loop": "loop = true" in tail or "loop=true" in tail,
        }
    return fps, bones, clips


def num(x):
    s = "%.5g" % x
    return "0" if s in ("-0", "-0.0") else s


def q_xyzw(q_wxyz):
    w, x, y, z = q_wxyz
    return (x, y, z, w)


# Every animation range in model.lua starts with one lead-in/blend frame that is
# not part of the motion (e.g. walk frame 699 has the body flipped 95 deg and
# shifted 6 units). The engine hides it behind its transition blend; we bake it
# out. The true loop is [f0+1 .. f1], with f1 matching f0+1.
def bake_track(keys, f0, f1, fps, pos_tol, rot_tol):
    lo = min(f0 + 1, f1)
    seg = [k for k in keys if lo <= k[0] <= f1]
    if not seg:
        seg = [min(keys, key=lambda k: abs(k[0] - lo))]
    if len(seg) > 2:
        seg = decimate_track(seg, [lo, f1], pos_tol, rot_tol)
    dur = max(f1 - lo, 1) / fps
    out = []
    for fr, p, _s, q in seg:
        x, y, z, w = q_xyzw(q)
        out.append([(fr - lo) / fps, (float(p[0]), float(p[1]), float(p[2])),
                    (x, y, z, w)])
    out[0][0] = 0.0
    if len(out) > 1:
        out[-1][0] = dur
    return out


def fmt_keys(track):
    parts = []
    for t, p, r in track:
        parts.append("{t=%s,p={%s,%s,%s},r={%s,%s,%s,%s}}" % (
            num(t), num(p[0]), num(p[1]), num(p[2]),
            num(r[0]), num(r[1]), num(r[2]), num(r[3])))
    return "{" + ",".join(parts) + "}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pos-tol", type=float, default=0.04)
    ap.add_argument("--rot-tol", type=float, default=1.2, help="degrees")
    args = ap.parse_args()

    fps, bones, clips = read_ranges()
    _, nodes, _, _, _ = parse(MODEL)
    by_name = {n.name: n for n in nodes}
    for b in bones:
        if b not in by_name:
            sys.exit("bone %r not in %s" % (b, MODEL))

    lines = [
        "-- GENERATED by b3d_opti_tools/bake_player_anims.py -- do not edit.",
        "-- Source: %s + clip_ranges.lua" % os.path.basename(MODEL),
        "return {",
        "\tversion = 1,",
        "\tfps = %d," % fps,
        "\tskeleton = {",
    ]
    for b in bones:
        n = by_name[b]
        parent = nodes[n.parent].name if n.parent >= 0 else False
        px, py, pz = n.rest_pos
        x, y, z, w = q_xyzw(n.rest_quat)
        lines.append("\t\t%s = {parent=%s, p={%s,%s,%s}, r={%s,%s,%s,%s}}," % (
            b, ('"%s"' % parent) if parent else "false",
            num(px), num(py), num(pz), num(x), num(y), num(z), num(w)))
    lines += ["\t},", "\tclips = {"]

    total = 0
    for name in sorted(clips):
        f0, f1 = clips[name]["range"]
        dur = max(f1 - min(f0 + 1, f1), 1) / fps  # lead-in frame f0 is dropped
        lines.append("\t\t%s = {loop=%s, dur=%s, bones={" % (
            name, "true" if clips[name]["loop"] else "false", num(dur)))
        for b in bones:
            n = by_name[b]
            if not n.keys:
                continue
            track = bake_track(n.keys, f0, f1, fps, args.pos_tol, args.rot_tol)
            total += len(track)
            lines.append("\t\t\t%s = %s," % (b, fmt_keys(track)))
        lines.append("\t\t}},")
    lines += ["\t},", "}", ""]

    open(OUT_LUA, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    size = os.path.getsize(OUT_LUA)
    print("wrote %s  (%d clips, %d keys total, %.1f KiB)" % (
        os.path.relpath(OUT_LUA, os.path.join(HERE, "..")),
        len(clips), total, size / 1024))


if __name__ == "__main__":
    main()
